src/Entity/Magacin.php
<?php

namespace App\Entity;
use App\Entity\Racun;
use App\Repository\MagacinRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=MagacinRepository::class)
 */
class Magacin
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $naziv_proizvoda;

    /**
     * @ORM\Column(type="integer")
     */
    private $stopa_pdv;

    /**
     * @ORM\Column(type="float")
     */
    private $prodajna_cena;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $valuta;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $opis;

    /**
     * @ORM\OneToMany(targetEntity=Racun::class, mappedBy="Magacin")
     */
    private $racuns;

    public function __construct()
    {
        $this->racuns = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNazivProizvoda(): ?string
    {
        return $this->naziv_proizvoda;
    }

    public function setNazivProizvoda(string $naziv_proizvoda): self
    {
        $this->naziv_proizvoda = $naziv_proizvoda;

        return $this;
    }

    public function getStopaPdv(): ?int
    {
        return $this->stopa_pdv;
    }

    public function setStopaPdv(int $stopa_pdv): self
    {
        $this->stopa_pdv = $stopa_pdv;

        return $this;
    }

    public function getProdajnaCena(): ?float
    {
        return $this->prodajna_cena;
    }

    public function setProdajnaCena(float $prodajna_cena): self
    {
        $this->prodajna_cena = $prodajna_cena;

        return $this;
    }

    public function getValuta(): ?string
    {
        return $this->valuta;
    }

    public function setValuta(string $valuta): self
    {
        $this->valuta = $valuta;

        return $this;
    }

    public function getOpis(): ?string
    {
        return $this->opis;
    }

    public function setOpis(string $opis): self
    {
        $this->opis = $opis;

        return $this;
    }

    /**
     * @return Collection|Racun[]
     */
    public function getRacuns(): Collection
    {
        return $this->racuns;
    }

    public function addRacun(Racun $racun): self
    {
        if (!$this->racuns->contains($racun)) {
            $this->racuns[] = $racun;
            $racun->setMagacin($this);
        }

        return $this;
    }

    public function removeRacun(Racun $racun): self
    {
        if ($this->racuns->removeElement($racun)) {
            // set the owning side to null (unless already changed)
            if ($racun->getMagacin() === $this) {
                $racun->setMagacin(null);
            }
        }

        return $this;
    }
}

src/Entity/Racun.php
<?php

namespace App\Entity;

use App\Repository\RacunRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=RacunRepository::class)
 */
class Racun
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Magacin::class, inversedBy="racuns")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Magacin;

    /**
     * @ORM\Column(type="date")
     */
    private $datum;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMagacin(): ?Magacin
    {
        return $this->Magacin;
    }

    public function setMagacin(?Magacin $Magacin): self
    {
        $this->Magacin = $Magacin;

        return $this;
    }

    public function getDatum(): ?\DateTimeInterface
    {
        return $this->datum;
    }

    public function setDatum(\DateTimeInterface $datum): self
    {
        $this->datum = $datum;

        return $this;
    }
}

src/Form/MagacinType.php
<?php

namespace App\Form;

use App\Entity\Magacin;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;


class MagacinType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('Naziv_proizvoda')
            ->add('Stopa_pdv', ChoiceType::class, [
                'choices' => [
                    '10%' => 10,
                    '20%' => 20
                ],
            ])
            ->add('Prodajna_Cena')
            ->add('Valuta', ChoiceType::class, [
                'choices' =>[
                    'RSD' =>'RSD',
                    'EUR' =>'EUR'
                    ]
            ])
            ->add('Opis',  TextareaType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Magacin::class,
        ]);
    }
}

src/Controller/MagacinController.php
<?php

namespace App\Controller;

use App\Entity\Magacin;
use App\Form\MagacinType;
use App\Repository\MagacinRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class MagacinController extends AbstractController
{
    /**
     * @Route("/", name="magacin_index", methods={"GET"})
     */
    public function index(MagacinRepository $magacinRepository): Response
    {
        return $this->render('magacin/index.html.twig', [
            'magacins' => $magacinRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="magacin_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $magacin = new Magacin();
        $form = $this->createForm(MagacinType::class, $magacin);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($magacin);
            $entityManager->flush();

            return $this->redirectToRoute('magacin_index');
        }

        return $this->render('magacin/new.html.twig', [
            'magacin' => $magacin,
            'form' => $form->createView(),
        ]);
    }
     /**
     * @Route("/racun", name="blog_index")
     */
    public function racun(Request $request): Response
    {   $magacin = new Magacin();
        $form = $this->createForm(MagacinType::class, $magacin);
        $form->handleRequest($request);
        return $this->render('magacin/racun.html.twig',[
            'form'=>$form->createView()
        ]);
    }

    /**
     * @Route("/{id}", name="magacin_show", methods={"GET"})
     */
    public function show(Magacin $magacin): Response
    {
        return $this->render('magacin/show.html.twig', [
            'magacin' => $magacin,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="magacin_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Magacin $magacin): Response
    {
        $form = $this->createForm(MagacinType::class, $magacin);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('magacin_index');
        }

        return $this->render('magacin/edit.html.twig', [
            'magacin' => $magacin,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="magacin_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Magacin $magacin): Response
    {
        if ($this->isCsrfTokenValid('delete'.$magacin->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($magacin);
            $entityManager->flush();
        }

        return $this->redirectToRoute('magacin_index');
    }
   
     

}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {% block stylesheets %}
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
        <link href="{{ asset('css/style.css') }}" rel="stylesheet"/>
        {% endblock %}
    </head>
    <body>
        {% block body %}
        {% endblock %}
        {% block javascripts %}<script src="js/main.js"></script>{% endblock %}
    </body>
</html>

templates/magacin/_delete_form.html.twig
<form method="post" action="{{ path('magacin_delete', {'id': magacin.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ magacin.id) }}">
    <button class="btn">Delete</button>
</form>

templates/magacin/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/magacin/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Magacin{% endblock %}

{% block body %}
    <h1>Edit Magacin</h1>

    {{ include('magacin/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('magacin_index') }}">back to list</a>

    {{ include('magacin/_delete_form.html.twig') }}
{% endblock %}

templates/magacin/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Magacin index{% endblock %}

{% block body %}
<!--<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="colapse navbar-collapse">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link"  href="{{ path('magacin_new') }}">Create new</a>
            </li>
        </ul>
    </div>
</nav>-->
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Naziv proizvoda</th>
                <th>Stopa PDV(%)</th>
                <th>Prodajna cena</th>
                <th>Valuta</th>
                <th>Opis</th>
            </tr>
        </thead>
        <tbody>
        {% for magacin in magacins %}
            <tr>
                <td>{{ magacin.id }}</td>
                <td>{{ magacin.nazivProizvoda }}</td>
                <td>{{ magacin.stopaPdv }}</td>
                <td>{{ magacin.prodajnaCena }}</td>
                <td>{{ magacin.valuta }}</td>
                <td>{{ magacin.opis }}</td>
                <td>
                    <a class="btn btn-danger" href="{{ path('magacin_show', {'id': magacin.id}) }}">show</a>
                    <a class="btn btn-primary" href="{{ path('magacin_edit', {'id': magacin.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    
{% endblock %}

templates/magacin/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Magacin{% endblock %}

{% block body %}
    
    <div class="create">
    {{ include('magacin/_form.html.twig') }}

    <a href="{{ path('magacin_index') }}">back to list</a>
    </div>
{% endblock %}

templates/magacin/racun.html.twig
{% extends "base.html.twig" %}

{% block body %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="colapse navbar-collapse">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link"  href="{{ path('magacin_new') }}">Create new</a>
            </li>
        </ul>
    </div>
</nav>
{{ include('magacin/_form.html.twig') }}
{% endblock %}

templates/magacin/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Magacin{% endblock %}

{% block body %}
    <h1>Magacin</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ magacin.id }}</td>
            </tr>
            <tr>
                <th>Naziv_proizvoda</th>
                <td>{{ magacin.nazivProizvoda }}</td>
            </tr>
            <tr>
                <th>Stopa_pdv</th>
                <td>{{ magacin.stopaPdv }}</td>
            </tr>
            <tr>
                <th>Prodajna_cena</th>
                <td>{{ magacin.prodajnaCena }}</td>
            </tr>
            <tr>
                <th>Valuta</th>
                <td>{{ magacin.valuta }}</td>
            </tr>
            <tr>
                <th>Opis</th>
                <td>{{ magacin.opis }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('magacin_index') }}">back to list</a>

    <a href="{{ path('magacin_edit', {'id': magacin.id}) }}">edit</a>

    {{ include('magacin/_delete_form.html.twig') }}
{% endblock %}